name: BuildRelease

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Build
        run: .\build.ps1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Xpass
          path: .\bin\Xpass\*.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{ github.event.head_commit.message }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: Xpass
          path: ./artifacts

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/*.exe
          asset_name: Xpass.exe
          asset_content_type: application/octet-stream
