name: BuildRelease

on: 
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: .\build.ps1

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Xpass
        path: 
          .\bin\Xpass\*.exe
